### ISSUE TITLE
Map is not in usable format

### ISSUE THREAD

**Issue by JohnathonNow** [dontworrybhappy/SnowGPS#9]
We need to convert the map from its current format to a format that is more meaningful.
This includes calculating the weights.
I suggest a script to convert `map.txt` non-destructively, so `maping.py` can still edit the map.

**Comment by JohnathonNow** [comment]
Ryan did the thing but refuses to mark the issue as solved.

**Comment by dontworrybhappy** [comment]
I tweaked mapmaker/convert.py to print an adjacency the '-1''s are delimiter to denote when a list of edges is completed. It first prints the vertex (x and y position) and then every adjacent edge.
